### ISSUE TITLE
JUnit objectbox faild to run

### ISSUE THREAD

**Issue by motis10** [objectbox/objectbox-java#245]
I have problems running my unit tests in Jenkins. 

1. Gradle build can not find io.objectbox:objectbox-linux:1.2.0. (but can find 1.1.0)

2. When using object-linux:1.1.0 or object-java:1.2.0 I get the following error on every test:
java.lang.NoClassDefFoundError: Could not initialize class io.objectbox.internal.NativeLibraryLoader
	at io.objectbox.BoxStore.<init>(BoxStore.java:170)
	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:259)

When using objectbox-windows:1.2.0 on my PC the tests run and pass.

**Comment by greenrobot** [comment]
Please try again, 1.2.0 for Linux should now be normally deployed.

**Comment by motis10** [comment]
We updated it but we still get the:
```
java.lang.NoClassDefFoundError: Could not initialize class io.objectbox.internal.NativeLibraryLoader
at io.objectbox.BoxStore.(BoxStore.java:170)
at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:259)

```

**Comment by greenrobot** [comment]
I just verified the build on Linux and it worked fine. Do you have more info? Was the stack trace complete?

**Comment by greenrobot** [comment]
Maybe I just reproduced; `libobjectbox-linux-x64.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found` - are you seeing something like this?

Maybe that'll help:

    sudo apt-get install libstdc++6

**Comment by greenrobot** [comment]
No response, closing this. Feel free to re-open if you still have the issue.

**Comment by int02h** [comment]
I've faced with the same problem when running unit tests on build machine with Ubuntu 16.04.5 LTS. Stacktrace is almost the same as provided above:
```
java.lang.NoClassDefFoundError: Could not initialize class io.objectbox.internal.NativeLibraryLoader
	at io.objectbox.BoxStore.<init>(BoxStore.java:189)
	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:352)
```

It worked well with Objectbox 2.0.0 but fails with 2.2.0.

It seems that problem in loading native library in static initializer of the class `NativeLibraryLoader`. I noticed you've changed library name. For example for my build it was libobjectbox-linux-x64.so but became libobjectbox-jni-linux-x64.so. I made sure that library with correct name appeared in project directory, but tests are still failed.

**Comment by int02h** [comment]
More info about .so:
ldd libobjectbox-jni-linux-x64.so 
./libobjectbox-jni-linux-x64.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./libobjectbox-jni-linux-x64.so)
	linux-vdso.so.1 =>  (0x00007ffce6fa7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f55344c4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f55341bb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5533fa5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5533d88000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55339be000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5534b21000)

**Comment by greenrobot-team** [comment]
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./libobjectbox-jni-linux-x64.so)`

This looks like a dependency of ObjectBox is missing.

Did you try the suggested fix `sudo apt-get install libstdc++6`?

@greenrobot Does the Linux binary have a dependency, [similar to the Visual C++ redistributable on Windows](https://docs.objectbox.io/java-desktop-apps#native-libraries)? Should this be added to the docs?
-ut

**Comment by int02h** [comment]
Of course I've read the thread so I've tried to install libstdc++6. But my build machine worked on Ubuntu 16. Update to version 18 has solved my problem. I think that Ubuntu 16 has older revision of libstdc++ than necessary for Objectbox on Linux.

**Comment by greenrobot-team** [comment]
`2.3.0` now supports Ubuntu 16.04 and newer (before Ubuntu 18.04 and newer).

https://docs.objectbox.io/
-ut

**Comment by Armaxis** [comment]
I'm having the same issue: two tests fail with either `java.lang.UnsatisfiedLinkError` or `java.lang.NoClassDefFoundError` when running on the build machine (CentOS 7 3.10.0-514.26.2.el7.x86_64) but are successful when running locally (Windows 10).

I'm using Objectbox `2.3.3`

**Comment by greenrobot** [comment]
CentOS is using quite old Linux kernels (3.10 is from 2013) so I am guessing the standard libs are ancient as well. Could you give us the output if you run `ldd libobjectbox-jni-linux-x64.so` (see https://github.com/objectbox/objectbox-java/issues/245#issuecomment-428598562)?.
