### ISSUE TITLE
NoClassDefFoundError: kotlin/text/Charsets

### ISSUE THREAD

**Issue by weiyf** [objectbox/objectbox-java#946]
```
注: [ObjectBox] Starting ObjectBox processor (debug: false, incremental: true)Exception in thread "Thread-509" java.lang.NoClassDefFoundError: kotlin/text/Charsets
	at io.objectbox.reporting.BasicBuildTracker.sendEvent(BasicBuildTracker.kt:166)
	at io.objectbox.reporting.BasicBuildTracker$sendEventAsync$1.run(BasicBuildTracker.kt:143)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: kotlin.text.Charsets
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 3 more
Caused by: java.lang.ClassNotFoundException: kotlin.text.Charsets
```

objectboxVersion 2.8.1
kotlinVersion 1.4.21
androidstudio 4.1.2

**Comment by greenrobot-team** [comment]
Thanks! Can you check that you depend on `kotlin-stdlib`. Your Android project should be configured like suggested at: https://developer.android.com/kotlin/add-kotlin

If that isn't the issue, please provide a small example project so we can reproduce this!

**Comment by greenrobot-team** [comment]
OK, I just also got this on one of our test projects. I'm confused since `kotlin.text.Charsets` does still exist in Kotlin `1.4.21`, as it did in the version the plugin is compile with (`1.3.72`).

A fix is simple: remove usage of `kotlin.text.Charsets` in the plugin.

**Comment by greenrobot-team** [comment]
This is fixed internally and will ship with the next update. From what I have seen the exception is safe to ignore (it happens in a separate thread) and should not affect how the processor works or the Gradle build completes.

**Comment by greenrobot-team** [comment]
With `2.9.0` this crash should no longer occur.
