### ISSUE TITLE
3.5.1 ToOneGetter error: wrong number of type arguments; required 2

### ISSUE THREAD

**Issue by jrjohn** [objectbox/objectbox-java#1115]
**Describe the bug**

ToOne annotation generator code error.
The following code works well on 3.4.0 but 3.5.0 and 3.5.1

**Code**
```
@Entity
public class Compliance
{
    @Id
    private long Id;

    public long getId() {
        return Id;
    }

    public void setId(long id) {
        Id = id;
    }

    public ToOne<Record> record;

    public ToOne<ComplianceRecord> complianceRecord;


    public Compliance()
    {

    }

}
```

The Errors:

**Basic info (please complete the following information):**
 - ObjectBox version [3.5.1]
 - Reproducibility: [always]
 - Device: [OnePlus 8T+ 5G]
 - OS: [Android 12]

**Logs, stack traces**
android/android/app/build/generated/ap_generated_sources/formalDebug/out/com/xxxx/model/entity/Compliance_.java:105: error: wrong number of type arguments; required 2
            new RelationInfo<>(Compliance_.__INSTANCE, Record_.__INSTANCE, recordId, new ToOneGetter<Compliance>() {

**Comment by greenrobot-team** [comment]
[Release 3.5.0](https://github.com/objectbox/objectbox-java/releases/tag/V3.5.0) has some breaking changes for generated code. Make sure to clean and re-compile your project to generate code that supports the new internal APIs.

**Comment by jrjohn** [comment]
I'm sorry, I forget to upgrade project level objectbox-gradle-plugin to 3.5.1. It works well after the upgrade. Thanks very much.

build.gradle(project) ====>
dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
        classpath 'com.google.gms:google-services:4.3.15'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'
        classpath "io.objectbox:objectbox-gradle-plugin:3.4.0"  <== forget upgrade this to 3.5.1
        classpath 'io.github.wurensen:gradle-android-plugin-aspectjx:3.3.2'
        classpath 'org.aspectj:aspectjtools:1.9.7'
        classpath 'org.aspectj:aspectjweaver:1.9.7'
    }


build.gradle(app) ===>
dependencies {
 testImplementation "io.objectbox:objectbox-linux:3.5.1"
 testImplementation "io.objectbox:objectbox-macos:3.5.1"
 testImplementation "io.objectbox:objectbox-windows:3.5.1"
 implementation "io.objectbox:objectbox-rxjava:3.5.1"
 implementation "io.objectbox:objectbox-android-objectbrowser:3.5.1"
 ..
}

**Comment by greenrobot-team** [comment]
Alright, closing this then.
